name: bump api cache daily

on:
  schedule:
    - cron: '3 3 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: bump API cache
      run: |
        uptime
        python3 --version 
        python3 build-cache.py
        git config --global user.name "API cache bump bot"
        git config --global user.email "lewurm+bot@gmail.com"
        git add docs/cache
        git commit -m "api cache: update"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/awattar-backtesting/awattar-backtesting.github.io.git main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
